workflows:
  android-workflow:
    name: Android Sample Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      android_signing:
        - cm_keystore_credentials
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "io.codemagic.sample.reactnative"
