workflows:
  android-workflow:
    name: React Native App Expo
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      # groups:
      #   - app_center_credentials
      android_signing:
        - solocmrn
      groups:
        - reactnative
        # - google_credentials
      vars:
        PACKAGE_NAME: "io.codemagic.sample.reactnative"
      node: latest
    scripts:
      - name: Install npm dependencies
        script: |
          cd $CM_BUILD_DIR
          yarn install --ignore-scripts
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Create Local Variables
        script: |
          echo "FB_CLIENT_ID=$FB_CLIENT_ID" >> .env
      - name: Clean Android build
        script: |
          cd android
          ./gradlew clean
      - name: Build Android release
        script: |
          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
          UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
          fi
          cd android
          ENVFILE=.env ./gradlew assembleRelease \
              -PversionCode=$UPDATED_BUILD_NUMBER \
              -PversionName=1.0.$UPDATED_BUILD_NUMBER
          # ./gradlew assembleStagingRelease \
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - solomon@codemagic.io
      # google_play:
      #   track: internal
      #   credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
      #   submit_as_draft: true
